services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app/backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/frontend/src
    stdin_open: true
    tty: true
  # postgres:
  #   image: postgres

  #   volumes:
  #     - data:/var/lib/postgresql/data
