version: "3.9"

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - ./:/usr/src/app/
      - ./staticfiles:/app/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
    command: /start
    
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    env_file:
      - ./.envs/.env.local
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data: {}
